### ISSUE TITLE
Error opening USS directory

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-explorer-vscode#2797]
**Describe the bug**

Opening a directory in USS results in error parsing JSON

```
[2024/03/22 08:47:47] [ERROR] Error: The get request appeared to succeed, but the response was not in the expected format:
Bad control character in string literal in JSON at position 1050 (line 10 column 18)
{
  errorDetails: r [Error]: The get request appeared to succeed, but the response was not in the expected format:
  Bad control character in string literal in JSON at position 1050 (line 10 column 18)
      at Function.parse (/Users/user/.vscode/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:29:406487)
      at Function.<anonymous> (/Users/user/.vscode/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:90:57741)
      at Generator.next (<anonymous>)
      at s (/Users/user/.vscode/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:90:57243)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    mDetails: {
      msg: 'The get request appeared to succeed, but the response was not in the expected format:\n' +
        'Bad control character in string literal in JSON at position 1050 (line 10 column 18)',
      stack: 'SyntaxError: Bad control character in string literal in JSON at position 1050 (line 10 column 18)\n' +
        '    at JSON.parse (<anonymous>)\n' +
        '    at Function.parse (/Users/user/.vscode/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:29:406463)\n' +
        '    at Function.<anonymous> (/Users/user/.vscode/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:90:57741)\n' +
        '    at Generator.next (<anonymous>)\n' +
        '    at s (/Users/user/.vscode/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:90:57243)\n' +
        '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
      additionalDetails: 'Bad control character in string literal in JSON at position 1050 (line 10 column 18)',
      causeErrors: SyntaxError: Bad control character in string literal in JSON at position 1050 (line 10 column 18)
          at JSON.parse (<anonymous>)
          at Function.parse (/Users/user/.vscode/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:29:406463)
          at Function.<anonymous> (/Users/user/.vscode/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:90:57741)
          at Generator.next (<anonymous>)
          at s (/Users/user/.vscode/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:90:57243)
          at processTicksAndRejections (node:internal/process/task_queues:95:5) {
        vslsStack: [
          CallSite {},
          CallSite {},
          CallSite {},
          CallSite {},
          CallSite {},
          CallSite {}
        ]
      }
    },
    mMessage: 'The get request appeared to succeed, but the response was not in the expected format:\n' +
      'Bad control character in string literal in JSON at position 1050 (line 10 column 18)',
    vslsStack: [ CallSite {}, CallSite {}, CallSite {}, CallSite {}, CallSite {} ]
  },
  label: 'pagent',
  moreInfo: 'Retrieving response from uss-file-list'
}
```

I would like to know if there is any workaround for this.

**Desktop (please complete the following information):**

- OS: macOS 
- Zowe Explorer Version: 2.15.1

**Comment by t1m0thyj** [comment]
IBM z/OSMF does not properly escape JSON responses when listing USS directories that contain filenames with special characters. We are waiting on this IBM RFE to be addressed: https://ibm-z-hardware-and-operating-systems.ideas.ibm.com/ideas/ZOS-I-3760

There is also a related issue in the Zowe CLI repo: https://github.com/zowe/zowe-cli/issues/1748

**Comment by EmmasBox** [comment]
This bug is still a problem in Zowe 3.0.2, I am unable to open my z/OS Unix home folder through Zowe Explorer because of one the files contains special characters.

**Comment by juler69** [comment]
I see the same error in v3.1.2 but for a different reason.  

I have a directory that contains a node.js application.  The directory name is 'dsapi'.  There are no filenames with special characters in that directory other than ones containing either '-' or '.'.  If I try to browse this directory I get the issue as described.

When I copy this exact directory to a fresh directory with a new name, say 'dsapi-b' I can open it no problem.

If however, I change the ownership of the new directory to anything else, then no matter what I do it will manifest the issue as described.  Even if I change it back to what it was before, I continue to see the issue as described.
