### ISSUE TITLE
Test Run Error When Using Latest Zowe Extension Version

### ISSUE THREAD

**Issue by sujatha2206** [zowe/zowe-explorer-vscode#3277]
**Describe the bug**

I am creating a test setup for my extension.My extension depends on the Zowe Explorer extension. When I use zowe: Zowe.vscode-extension-for-zowe@2.18.0, my tests run successfully. However, when I use the latest version, the tests do not run, and I receive the following error:

Failed to run tests: TestRunFailedError: Test run failed with code 1 at ChildProcess.onProcessClosed (C:\Users\ctron\out\runTest.js:110:24)

**To Reproduce**

Steps to Reproduce the Behavior:

Go to the extension that depends on the Zowe extension.
Create a test setup using VS Code APIs: @vscode/test-cli and @vscode/test-electron (see: [Testing Extensions](https://code.visualstudio.com/api/working-with-extensions/testing-extension)).
Run: npm run test, whether using the test CLI or the advanced runner.
Observe the error: Failed to run tests: TestRunFailedError: Test run failed with code 1 at ChildProcess.onProcessClosed (C:\Users\ctron\out\runTest.js:110:24).

**Expected behavior**

Should run test cases

**Screenshots**

**Desktop (please complete the following information):**

- OS:Windows
- Zowe Explorer Version:3.2.0
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Comment by sujatha2206** [comment]
Let me know If you need any further information

**Comment by traeok** [comment]
Hi @sujatha2206,

Thanks for the bug report. I have a couple questions before moving forward with reproducing the issue:

1. Has your extension been updated to support Zowe Explorer v3? If your extension can run tests successfully alongside Zowe Explorer v2.18.0, but the same extension version fails with v3, you might need to update your extension to be compatible with v3. See this wiki page for more information on how to upgrade to v3: https://github.com/zowe/zowe-explorer-vscode/wiki/v3-Changes-for-Users-and-Extenders
2. In the attached error message, I see two errors coming from VS Code. Can you try passing the arguments mentioned in the errors to VS Code as part of your test command so that we can get more context on the error?
  - `--trace-deprecation`
  - `--force-node-api-uncaught-exceptions-policy=true`

Thanks!

**Comment by sujatha2206** [comment]
Hi @traeok 
1.My extension updated to latest zowe version,my development environment is working fine.
2. I have added the arguments, but it still started the VSCode instance and then exited immediately.
![image](https://github.com/user-attachments/assets/520ba601-b039-474a-a890-7e24e2240e9f)

**Comment by traeok** [comment]
Thanks for the quick follow up. I'm working on reproducing this issue with a sample extension and will move forward from there.

One more quick question: Do you happen to have Zowe v1 profiles in place for your project, but without an available team config? It's possible that Zowe Explorer is reloading the window to handle an upgrade scenario from v1 -> v3 - unfortunately this can't be avoided since a reload is needed when upgrading from v1 to v3, but it's one possible reason why the extension is exiting.

**Comment by sujatha2206** [comment]
I am working on testing my extension, but initially, it opens the VSCode instance and then immediately closes. If this is a profile issue, how is our development working fine?

Note: My initial test case only involves getting the Zowe extension. If this were a profile issue, at least the first test case should run, right?

**Comment by sujatha2206** [comment]
We don't have v1 profiles,profiles are being defined in team config,

**Comment by traeok** [comment]
@sujatha2206, quick question for clarification: does your extension depend on Zowe Explorer? or does it try to download Zowe Explorer when not installed?

When testing with an extension that depends on Zowe Explorer, I'm able to run tests alongside Zowe Explorer v3. I used the `helloworld-test-example` extension from VS Code's extension samples and added a line that prints the registered API types from Zowe Explorer API. When running the tests, I see the message that I added, my extension activates alongside Zowe Explorer and the test is successful.

```typescript
const zeApi = vscode.extensions.getExtension("Zowe.vscode-extension-for-zowe")?.exports as Types.IApiRegisterClient;
	vscode.window.showInformationMessage(zeApi.registeredApiTypes().join(" "));
```

Here's the notification in action, beside the "Start all tests" message in the sample test:
![image](https://github.com/user-attachments/assets/2f28cd91-8b0d-4821-af9e-d2e6a8854d7d)

Here's the sample test, for reference:
```typescript
suite('Extension Test Suite', () => {
	vscode.window.showInformationMessage('Start all tests.');

	test('Sample test', async () => {
		assert.strictEqual([1, 2, 3].indexOf(5), -1);
		assert.strictEqual([1, 2, 3].indexOf(0), -1);
		await new Promise((resolve, _reject) => setTimeout(() => resolve(null), 1000));
	});
});
```

**Comment by sujatha2206** [comment]
Our extension depends on zowe explorer.

**Comment by traeok** [comment]
I can push the modified sample extension to a personal repo, if you'd like to test how the VS Code test CLI behaves with the sample on your machine. As it currently stands, I'm unable to reproduce the error when using a sample extension that depends on Zowe Explorer v3 - I'm able to grab its exported API and use it as normal. Maybe this is due to an unhandled error that occurs when running tests w/ the `zopendebug` extension during activation?

If you have any additional errors to provide from your debug console or terminal, that might help to reproduce the issue. Is it possible to add a sleep to your extension tests, to catch any errors in the VS Code window before it fails and exits?

**Comment by sujatha2206** [comment]
Thanks I will look into it.please share a sample extension to my personal repo

**Comment by sujatha2206** [comment]
@traeok  one question If it is unhandled error how does it works in zowe 2.18 version

**Comment by traeok** [comment]
@sujatha2206,

If you are accessing the Zowe Explorer API using similar logic to the sample above, you should be able to use the API without issue, regardless of what Zowe Explorer version is installed. It's possible that logic during your extension's activation causes an issue with v3, _specifically_ when running tests, but its not clear without additional context (such as a snippet of activation logic that uses the Zowe Explorer API).

If possible, please provide steps to reproduce the bug outside of the context of your extension. From my testing, I am unable to reproduce the issue with the sample Zowe Explorer extender. If I change the type import in the above sample to be compatible with v2 of Zowe Explorer API, the extension tests also pass with v2.18, suggesting that it could be an extension-specific issue.

**Comment by sujatha2206** [comment]
@traeok I have now disabled the Zowe extension, and I can see that some of my test cases are successful. This may be an integration issue with my extension and Zowe.

**Comment by traeok** [comment]
Hi @sujatha2206,

I was just wondering if you had an update on whether you resolved your extension integration issue with Zowe Explorer v3?

Thanks!

**Comment by sujatha2206** [comment]
HI @traeok issue is not resolved yet, we are still investigating it.

**Comment by traeok** [comment]
Closing this issue due to inactivity. If you're still encountering this issue, please re-open it with steps to reproduce. Thanks!
