### ISSUE TITLE
Regression: Unregistered Profile type causing Type error during activation

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3352]
**Describe the bug**

Team config has cics profile type but cics VSC ext not installed, returns type error missing ISession

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: macos
- Zowe Explorer Version: main branch, not seen in 3.0.3
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

error from log
[ERROR] TypeError: Cannot read properties of undefined (reading 'ISession')
{
  errorDetails: [TypeError: Cannot read properties of undefined (reading 'ISession')
  	at fe.getProfileSessionWithVscProxy 
(/Users/rudypflores/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.0-SNAPSHOT/out/src/main.extension.js:12:44236)
  	at Q.getSession (/Users/rudypflores/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.0-SNAPSHOT/out/src/main.extension.js:12:48034)
  	at Ai.<anonymous> (/Users/rudypflores/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.0-SNAPSHOT/out/src/main.extension.js:139:43561)
  	at Generator.next (<anonymous>)
  	at /Users/rudypflores/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.0-SNAPSHOT/out/src/main.extension.js:139:37059
  	at new Promise (<anonymous>)
  	at xe (/Users/rudypflores/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.0-SNAPSHOT/out/src/main.extension.js:139:36879)
  	at Ai.addSingleSession (/Users/rudypflores/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.0-SNAPSHOT/out/src/main.extension.js:139:43393)
  	at Ai.<anonymous> (/Users/rudypflores/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.0-SNAPSHOT/out/src/main.extension.js:64:45199)
  	at Generator.next (<anonymous>)
  	at r (/Users/rudypflores/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.0-SNAPSHOT/out/src/main.extension.js:64:38053)],
  apiType: 'uss',
  profile: undefined
}

**Comment by zFernand0** [comment]
Hey Billie,

I don't believe that this has been fixed yet 😢 
The error seems to be related to the `gretSession` returning undefined.

If we look closely, 
> [ERROR] TypeError: Cannot read properties of undefined (reading 'ISession')

That means that `session` is undefined, and we are trying to access `ISession`
So, checkoing for `session.ISession` won't help 😢 
<img width="392" alt="image" src="https://github.com/user-attachments/assets/f4c7a801-d095-4477-b44e-056019aac5ed" />

**Comment by JillieBeanSim** [comment]
Hey @zFernand0 that would be the [issue](https://github.com/zowe/zowe-explorer-vscode/issues/3337) we created when Proxy support was initially added and we discussed that in the [PR](https://github.com/zowe/zowe-explorer-vscode/pull/3291)

**Comment by zFernand0** [comment]
Hey Billie, I totally agree.
I just reopened this since I can still reproduce it in `main` 🙏
